### ISSUE TITLE
Error when creating a new user in WP after Google authentication

### ISSUE THREAD

**Issue by Shinkaiser** [pantheon-systems/wp-saml-auth#180]
Hi all.

First of all, thank you for this amazing plugin. It seems exactly what I was looking for.

I have a question related with creating new users in WP just after Google Login.

If the users already exist in WP, there is no problem to log them in after Google SSO but if the users are new to create, a message appears with this error:

> Cannot create a user with an empty login name

I have activated the "Auto Provision" feature that should create a new WP user upon login but it seems it is not working.

What could be the cause?

Thank you so much in advance.

Kind regards.

**Comment by danielbachhuber** [comment]
Hey @Shinkaiser,

You're welcome :)

I tried setting up Google Apps SAML to see if I could reproduce this issue but I'm getting the `app_not_configured_for_user` error right now so I might need to wait a bit.

By default, WP SAML Auth expects the `user_login` attribute to be `uid` in the SAML response:

https://github.com/pantheon-systems/wp-saml-auth/blob/7696ff8da58984670bb1305bddefc7ae7f449de9/wp-saml-auth.php#L125

Can you add a `var_dump( $attributes ); exit;` under the following line, and verify there's a `uid` in the SAML response?

https://github.com/pantheon-systems/wp-saml-auth/blob/ddbf287d54d1dd09feb2a9bd56ccd01c09e452b0/inc/class-wp-saml-auth.php#L246

If there isn't, you might be able to change the WP SAML Auth `user_login_attribute` configuration attribute to use `mail` instead of `uid`. I'm pretty sure WordPress is fine with an email address in the `user_login` field.

Let me know what you find!

**Comment by Shinkaiser** [comment]
Thank you @danielbachhuber !

I will try with your suggestion.

BR

**Comment by danielbachhuber** [comment]
@Shinkaiser Were you able to work this out?

**Comment by alexfornuto** [comment]
I was stuck at this same spot, and in the plugin settings page replaced the mapping for `user_login` with `email` (not `mail`) to solve. Thanks!

**Comment by danielbachhuber** [comment]
@alexfornuto Great! Thanks for the update 😄

**Comment by alexfornuto** [comment]
@Shinkaiser some newly proposed documentation updates may help you get the proper mapping for new users. It's temporarily staged [here](https://5501wordpr-static-docs.pantheonsite.io/docs/guides/wordpress-google-sso/access-and-mapping)

**Comment by Shinkaiser** [comment]
Sorry for my late response!

I have tested today and [this](https://5501wordpr-static-docs.pantheonsite.io/docs/guides/wordpress-google-sso/access-and-mapping) worked like a charm.

Thank you @alexfornuto for the additional work :)
