### ISSUE TITLE
SimpleSAMLPHP doesn't work when installed to ~/code/simplesamlphp

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-saml-auth#23]
But it does work when installed to `~/code/simplesaml`

See https://github.com/pantheon-systems/wp-saml-auth/pull/21/commits/f71194d85076aab03e3acb3d0f93c9774b9cb709

Who knows why? I don't know why.

**Comment by larcher** [comment]
I think there's something special about the path `simplesaml`. It's mentioned in the Pantheon nginx config file...

**Comment by joshkoenig** [comment]
This is due to nginx configuration on Pantheon which requires the core library to be installed at a specific URL so that direct requests to SimpleSamlPHP endpoints get the kind of legacy PHP app treatment required by the toolkit. :\

Note that we recommend actually installing simplsaml in the `private` directory, and creating a symlink to allow web routes to work without exposing certificates, etc:

https://pantheon.io/docs/shibboleth-sso/

**Comment by danielbachhuber** [comment]
Adding the following to the README:

> On Pantheon, the SimpleSAMLphp web directory needs to be symlinked to `~/code/simplesaml` to be properly handled by Nginx. [Read the docs](https://pantheon.io/docs/shibboleth-sso/) for more details about configuring SimpleSAMLphp on Pantheon.
