### ISSUE TITLE
Auto Provision - Not Allowing Login If Email Exist

### ISSUE THREAD

**Issue by adamrpostjr** [pantheon-systems/wp-saml-auth#363]
When a pre-existing user logs in, it fails when auto Provision is turned on.

It would be nice if the user were to just login.

**Comment by jazzsequence** [comment]
Pre-existing user on the IdP or pre-existing user in WordPress?

**Comment by adamrpostjr** [comment]
WordPress, 

For example, when I set up SSO login, and a user (who was previously setup on wordpress) tries to log in with the SSO, It fails.

**Comment by jazzsequence** [comment]
SAML SSO takes the place of password authentication. If a SAML auth fails and was passed back to WordPress, the user would _still_ need to authenticate with a password in order to log into the site. This is already possible when `Permit WordPress login` is set. You wouldn't want to pass a failed SAML authentication straight through to your WordPress dashboard if a user with that login existed, because then I could just log into your site if I knew what email you used. 

By default, Auto Provision is enabled, so if a WordPress user does not exist that matches the SAML identity, a new user (with the default role, generally subscriber) is created. This can be disabled to force SAML logins to only be allowed if a WordPress user already exists. 

I'm not sure what's going on specifically in your instance if a user is not created by the SAML authentication or if the user doesn't actually exist, but it's worth noting that SAML logins will use the email address as the username. So, if I have a WP user `chris` with the email address `chris@whatever.dev` and I try to authenticate via SAML with `chris@whatever.dev`, the Identity Provider is going to try to log in `chris@whatever.dev` and, if it does, it's going to say to WordPress "a user with the username `chris@whatever.dev` has successfully authenticated." If a user with that username doesn't exist (which it won't, because my username is `chris`), it will either create a new subscriber user (if Auto Provision is turned on) or it will fail to authenticate (if it is turned off, because `"chris" != "chris@whatever.dev`).

**Comment by adamrpostjr** [comment]
I am going to take a look at our setup later today. 
I will close this out with a note of what I found the problem to be!

Thanks for you help.

**Comment by adamrpostjr** [comment]
This was my fault
