### ISSUE TITLE
Customising Login 

### ISSUE THREAD

**Issue by mobcdi** [pantheon-systems/wp-saml-auth#75]
I've installed the plugin and its detected my simplesaml setup. My question is whether its possible to customise the login details to change "Use one-click authentication" to something else?

**Comment by danielbachhuber** [comment]
> My question is whether its possible to customise the login details to change "Use one-click authentication" to something else?

It's possible, but it requires a little bit of a hack right now.

Could you share more detail on what you want to change? Is it just the text, or is it the markup too?

**Comment by mobcdi** [comment]
I'd settle for changing the text value and maybe the Wordpress logo over it unless thats default wordpress

**Comment by danielbachhuber** [comment]
Ok.

Adding a `wp_saml_auth_login_strings` filter in #77 so the text values can be modified.

Changing the WordPress logo is outside the scope of this plugin, because this plugin doesn't render the WordPress logo in the first place.

However, here's a code snippet you can use to specify a login logo:

```
add_action( 'login_head', function() {
	?>
	<style>
		.login h1 a {
			background-image: url( 'http://example.org/logo.jpg' );
			width: 300px;
			height: 70px;
			background-size: 300px;
		}
	</style>
	<?php
});
```
